import {ROUTES} from "../config/routes.js";


export const createStore = (t) => ({
    services: [
        {
            id: 1,
            url: ROUTES.ADJUSTMENT_OF_GAS_DISTRIBUTION_SYSTEM,
            mobileImg: '/adjustmentOfGasDistributionSystemMobile.jpg',
            desktopImg: '/adjustmentOfGasDistributionSystemBig.jpg',
            desc: t("servicesPage.adjustmentOfGasDistributionSystem.desc"),
            name: t("servicesPage.adjustmentOfGasDistributionSystem.name"),
            smallDesc: t("servicesPage.adjustmentOfGasDistributionSystem.smallDesc"),
            additionTitle: t("servicesPage.adjustmentOfGasDistributionSystem.additionTitle"),
            additionTitleList: [
                {
                    id: 1,
                    title: t("servicesPage.adjustmentOfGasDistributionSystem.title_1"),
                    text: t("servicesPage.adjustmentOfGasDistributionSystem.addition_1"),
                },
                {
                    id: 2,
                    title: t("servicesPage.adjustmentOfGasDistributionSystem.title_2"),
                    text: t("servicesPage.adjustmentOfGasDistributionSystem.addition_2"),
                },
                {
                    id: 3,
                    title: t("servicesPage.adjustmentOfGasDistributionSystem.title_3"),
                    text: t("servicesPage.adjustmentOfGasDistributionSystem.addition_3"),
                },
                {
                    id: 4,
                    title: t("servicesPage.adjustmentOfGasDistributionSystem.title_4"),
                    text: t("servicesPage.adjustmentOfGasDistributionSystem.addition_4"),
                },
                {
                    id: 5,
                    title: t("servicesPage.adjustmentOfGasDistributionSystem.title_5"),
                    text: t("servicesPage.adjustmentOfGasDistributionSystem.addition_5"),
                },
            ],
            additionImg: '/adjustmentOfGasDistributionSystemOne.png',
        },
        {
            id: 2,
            url: ROUTES.ADJUSTMENT_OF_EQUIPMENT_UNDER_EXCESS_PRESSURE,
            mobileImg: '/adjustmentOfEquipmentUnderExcessPressureMobile.jpg',
            desktopImg: '/adjustmentOfEquipmentUnderExcessPressureBig.jpg',
            name: t("servicesPage.adjustmentOfEquipmentUnderExcessPressure.name"),
            desc: t("servicesPage.adjustmentOfEquipmentUnderExcessPressure.desc"),
            smallDesc: t("servicesPage.adjustmentOfEquipmentUnderExcessPressure.smallDesc"),
            additionTitle: t("servicesPage.adjustmentOfEquipmentUnderExcessPressure.additionTitle"),
            additionTitleList: [
                {
                    id: 1,
                    title: t("servicesPage.adjustmentOfEquipmentUnderExcessPressure.title_1"),
                    text: t("servicesPage.adjustmentOfEquipmentUnderExcessPressure.addition_1"),
                },
                {
                    id: 2,
                    title: t("servicesPage.adjustmentOfEquipmentUnderExcessPressure.title_2"),
                    text: t("servicesPage.adjustmentOfEquipmentUnderExcessPressure.addition_2"),
                },
                {
                    id: 3,
                    title: t("servicesPage.adjustmentOfEquipmentUnderExcessPressure.title_3"),
                    text: t("servicesPage.adjustmentOfEquipmentUnderExcessPressure.addition_3"),
                },
                {
                    id: 4,
                    title: t("servicesPage.adjustmentOfEquipmentUnderExcessPressure.title_4"),
                    text: t("servicesPage.adjustmentOfEquipmentUnderExcessPressure.addition_4"),
                },
            ],
            additionImg: '/adjustmentOfEquipmentUnderExcessPressureOne.png',
        },
        {
            id: 3,
            url: ROUTES.ADJUSTMENT_OF_TECHNICAL_DEVICES,
            mobileImg: '/adjustmentOfTechnicalDevicesMobile.jpg',
            desktopImg: '/adjustmentOfTechnicalDevicesBig.jpg',
            name: t("servicesPage.adjustmentOfTechnicalDevices.name"),
            desc: t("servicesPage.adjustmentOfTechnicalDevices.desc"),
            smallDesc: t("servicesPage.adjustmentOfTechnicalDevices.smallDesc"),
            additionTitle: t("servicesPage.adjustmentOfTechnicalDevices.additionTitle"),
            additionTitleList: [
                {
                    id: 1,
                    title: t("servicesPage.adjustmentOfTechnicalDevices.title_1"),
                    text: t("servicesPage.adjustmentOfTechnicalDevices.addition_1"),
                },
                {
                    id: 2,
                    title: t("servicesPage.adjustmentOfTechnicalDevices.title_2"),
                    text: t("servicesPage.adjustmentOfTechnicalDevices.addition_2"),
                },
                {
                    id: 3,
                    title: t("servicesPage.adjustmentOfTechnicalDevices.title_3"),
                    text: t("servicesPage.adjustmentOfTechnicalDevices.addition_3"),
                },
            ],
            additionImg: '/adjustmentOfTechnicalDevicesOne.png',
        },
        {
            id: 4,
            url: ROUTES.MAINTENANCE_OF_GAS_DISTRIBUTION_SYSTEM,
            mobileImg: '/maintenanceOfGasDistributionSystemMobile.jpg',
            desc: t("servicesPage.maintenanceOfGasDistributionSystem.desc"),
            desktopImg: '/maintenanceOfGasDistributionSystemBig.jpg',
            name: t("servicesPage.maintenanceOfGasDistributionSystem.name"),
            smallDesc: t("servicesPage.maintenanceOfGasDistributionSystem.smallDesc"),
            additionTitle: t("servicesPage.maintenanceOfGasDistributionSystem.additionTitle"),
            additionTitleList: [
                {
                    id: 1,
                    title: t("servicesPage.maintenanceOfGasDistributionSystem.title_1"),
                    text: t("servicesPage.maintenanceOfGasDistributionSystem.addition_1"),
                },
                {
                    id: 2,
                    title: t("servicesPage.maintenanceOfGasDistributionSystem.title_2"),
                    text: t("servicesPage.maintenanceOfGasDistributionSystem.addition_2"),
                },
                {
                    id: 3,
                    title: t("servicesPage.maintenanceOfGasDistributionSystem.title_3"),
                    text: t("servicesPage.maintenanceOfGasDistributionSystem.addition_3"),
                },
                {
                    id: 4,
                    title: t("servicesPage.maintenanceOfGasDistributionSystem.title_4"),
                    text: t("servicesPage.maintenanceOfGasDistributionSystem.addition_4"),
                },
            ],
            additionImg: '/maintenanceOfGasDistributionSystemOne.png',
        },
        {
            id: 5,
            url: ROUTES.SERVICING_EQUIPMENT_UNDER_EXCESS_PRESSURE,
            mobileImg: '/servicingEquipmentUnderExcessPressureMobile.jpg',
            desc: t("servicesPage.servicingEquipmentUnderExcessPressure.desc"),
            desktopImg: '/servicingEquipmentUnderExcessPressureBig.jpg',
            name: t("servicesPage.servicingEquipmentUnderExcessPressure.name"),
            smallDesc: t("servicesPage.servicingEquipmentUnderExcessPressure.smallDesc"),
            additionTitle: t("servicesPage.servicingEquipmentUnderExcessPressure.additionTitle"),
            additionTitleList: [
                {
                    id: 1,
                    title: t("servicesPage.servicingEquipmentUnderExcessPressure.title_1"),
                    text: t("servicesPage.servicingEquipmentUnderExcessPressure.addition_1"),
                },
                {
                    id: 2,
                    title: t("servicesPage.servicingEquipmentUnderExcessPressure.title_2"),
                    text: t("servicesPage.servicingEquipmentUnderExcessPressure.addition_2"),
                },
                {
                    id: 3,
                    title: t("servicesPage.servicingEquipmentUnderExcessPressure.title_3"),
                    text: t("servicesPage.servicingEquipmentUnderExcessPressure.addition_3"),
                },
                {
                    id: 4,
                    title: t("servicesPage.servicingEquipmentUnderExcessPressure.title_4"),
                    text: t("servicesPage.servicingEquipmentUnderExcessPressure.addition_4"),
                },
            ],
            additionImg: '/servicingEquipmentUnderExcessPressureOne.jpg',
        },
        {
            id: 6,
            url: ROUTES.MAINTENANCE_OF_TECHNICAL_DEVICES,
            mobileImg: '/maintenanceOfTechnicalDevicesMobile.jpg',
            desc: t("servicesPage.maintenanceOfTechnicalDevices.desc"),
            desktopImg: '/maintenanceOfTechnicalDevicesBig.jpg',
            name: t("servicesPage.maintenanceOfTechnicalDevices.name"),
            smallDesc: t("servicesPage.maintenanceOfTechnicalDevices.smallDesc"),
            additionTitle: t("servicesPage.maintenanceOfTechnicalDevices.additionTitle"),
            additionTitleList: [
                {
                    id: 1,
                    title: t("servicesPage.maintenanceOfTechnicalDevices.title_1"),
                    text: t("servicesPage.maintenanceOfTechnicalDevices.addition_1"),
                },
                {
                    id: 2,
                    title: t("servicesPage.maintenanceOfTechnicalDevices.title_2"),
                    text: t("servicesPage.maintenanceOfTechnicalDevices.addition_2"),
                },
                {
                    id: 3,
                    title: t("servicesPage.maintenanceOfTechnicalDevices.title_3"),
                    text: t("servicesPage.maintenanceOfTechnicalDevices.addition_3"),
                },
            ],
            additionImg: '/maintenanceOfTechnicalDevicesOne.jpg',
        },
        {
            id: 7,
            url: ROUTES.INSTALLATION_OF_EQUIPMENT_UNDER_EXCESS_PRESSURE,
            mobileImg: '/installationOfEquipmentUnderExcessPressureMobile.jpg',
            desc: t("servicesPage.installationOfEquipmentUnderExcessPressure.desc"),
            desktopImg: '/installationOfEquipmentUnderExcessPressureBig.jpg',
            name: t("servicesPage.installationOfEquipmentUnderExcessPressure.name"),
            smallDesc: t("servicesPage.installationOfEquipmentUnderExcessPressure.smallDesc"),
            additionTitle: t("servicesPage.installationOfEquipmentUnderExcessPressure.additionTitle"),
            additionTitleList: [
                {
                    id: 1,
                    title: t("servicesPage.installationOfEquipmentUnderExcessPressure.title_1"),
                    text: t("servicesPage.installationOfEquipmentUnderExcessPressure.addition_1"),
                },
                {
                    id: 2,
                    title: t("servicesPage.installationOfEquipmentUnderExcessPressure.title_2"),
                    text: t("servicesPage.installationOfEquipmentUnderExcessPressure.addition_2"),
                },
                {
                    id: 3,
                    title: t("servicesPage.installationOfEquipmentUnderExcessPressure.title_3"),
                    text: t("servicesPage.installationOfEquipmentUnderExcessPressure.addition_3"),
                },
                {
                    id: 4,
                    title: t("servicesPage.installationOfEquipmentUnderExcessPressure.title_4"),
                    text: t("servicesPage.installationOfEquipmentUnderExcessPressure.addition_4"),
                },
            ],
            additionImg: '/installationOfEquipmentUnderExcessPressureOne.jpg',
        },
        {
            id: 8,
            url: ROUTES.INSTALLATION_OF_TECHNICAL_DEVICES,
            mobileImg: '/installationOfTechnicalDevicesMobile.jpg',
            desc: t("servicesPage.installationOfTechnicalDevices.desc"),
            desktopImg: '/installationOfTechnicalDevicesBig.jpg',
            name: t("servicesPage.installationOfTechnicalDevices.name"),
            smallDesc: t("servicesPage.installationOfTechnicalDevices.smallDesc"),
            additionTitle: t("servicesPage.installationOfTechnicalDevices.additionTitle"),
            additionTitleList: [
                {
                    id: 1,
                    title: t("servicesPage.installationOfTechnicalDevices.title_1"),
                    text: t("servicesPage.installationOfTechnicalDevices.addition_1"),
                },
                {
                    id: 2,
                    title: t("servicesPage.installationOfTechnicalDevices.title_2"),
                    text: t("servicesPage.installationOfTechnicalDevices.addition_2"),
                },
                {
                    id: 3,
                    title: t("servicesPage.installationOfTechnicalDevices.title_3"),
                    text: t("servicesPage.installationOfTechnicalDevices.addition_3"),
                },
                {
                    id: 4,
                    title: t("servicesPage.installationOfTechnicalDevices.title_4"),
                    text: t("servicesPage.installationOfTechnicalDevices.addition_4"),
                },
            ],
            additionImg: '/installationOfTechnicalDevicesOne.jpg',
        },
        {
            id: 9,
            url: ROUTES.INSTALLATION_OF_GAS_DISTRIBUTION_SYSTEM_FACILITIES,
            mobileImg: '/installationOfGasDistributionSystemFacilitiesMobile.jpg',
            desc: t("servicesPage.installationOfGasDistributionSystemFacilities.desc"),
            desktopImg: '/installationOfGasDistributionSystemFacilitiesBig.jpg',
            name: t("servicesPage.installationOfGasDistributionSystemFacilities.name"),
            smallDesc: t("servicesPage.installationOfGasDistributionSystemFacilities.smallDesc"),
            additionTitle: t("servicesPage.installationOfGasDistributionSystemFacilities.additionTitle"),
            additionTitleList: [
                {
                    id: 1,
                    title: t("servicesPage.installationOfGasDistributionSystemFacilities.title_1"),
                    text: t("servicesPage.installationOfGasDistributionSystemFacilities.addition_1"),
                },
                {
                    id: 2,
                    title: t("servicesPage.installationOfGasDistributionSystemFacilities.title_2"),
                    text: t("servicesPage.installationOfGasDistributionSystemFacilities.addition_2"),
                },
                {
                    id: 3,
                    title: t("servicesPage.installationOfGasDistributionSystemFacilities.title_3"),
                    text: t("servicesPage.installationOfGasDistributionSystemFacilities.addition_3"),
                },
                {
                    id: 4,
                    title: t("servicesPage.installationOfGasDistributionSystemFacilities.title_4"),
                    text: t("servicesPage.installationOfGasDistributionSystemFacilities.addition_4"),
                },
                {
                    id: 5,
                    title: t("servicesPage.installationOfGasDistributionSystemFacilities.title_5"),
                    text: t("servicesPage.installationOfGasDistributionSystemFacilities.addition_5"),
                },
            ],
            additionImg: '/installationOfGasDistributionSystemFacilitiesOne.png',
        },
        {
            id: 10,
            url: ROUTES.FOUNDATION_CONSTRUCTION,
            mobileImg: '/foundationConstructionMobile.png',
            desc: t("servicesPage.foundationConstruction.desc"),
            desktopImg: '/foundationConstructionBig.jpg',
            name: t("servicesPage.foundationConstruction.name"),
            smallDesc: t("servicesPage.foundationConstruction.smallDesc"),
            additionTitle: t("servicesPage.foundationConstruction.additionTitle"),
            additionTitleList: [
                {
                    id: 1,
                    title: t("servicesPage.foundationConstruction.title_1"),
                    text: t("servicesPage.foundationConstruction.addition_1"),
                },
                {
                    id: 2,
                    title: t("servicesPage.foundationConstruction.title_2"),
                    text: t("servicesPage.foundationConstruction.addition_2"),
                },
                {
                    id: 3,
                    title: t("servicesPage.foundationConstruction.title_3"),
                    text: t("servicesPage.foundationConstruction.addition_3"),
                },
                {
                    id: 4,
                    title: t("servicesPage.foundationConstruction.title_4"),
                    text: t("servicesPage.foundationConstruction.addition_4"),
                },
                {
                    id: 5,
                    title: t("servicesPage.foundationConstruction.title_5"),
                    text: t("servicesPage.foundationConstruction.addition_5"),
                },
                {
                    id: 6,
                    title: t("servicesPage.foundationConstruction.title_6"),
                    text: t("servicesPage.foundationConstruction.addition_6"),
                },
                {
                    id: 7,
                    title: t("servicesPage.foundationConstruction.title_7"),
                    text: t("servicesPage.foundationConstruction.addition_7"),
                },
                {
                    id: 8,
                    title: t("servicesPage.foundationConstruction.title_8"),
                    text: t("servicesPage.foundationConstruction.addition_8"),
                },
                {
                    id: 9,
                    title: t("servicesPage.foundationConstruction.title_9"),
                    text: t("servicesPage.foundationConstruction.addition_9"),
                },
                {
                    id: 10,
                    title: t("servicesPage.foundationConstruction.title_10"),
                    text: t("servicesPage.foundationConstruction.addition_10"),
                },
            ],
            additionImg: '/foundationConstructionOne.png',
            supportStructuresTitle: t("servicesPage.foundationConstruction.supportStructuresTitle"),
            supportStructures_1: t("servicesPage.foundationConstruction.supportStructures_1"),
            supportStructures_2: t("servicesPage.foundationConstruction.supportStructures_2"),
        },
        {
            id: 11,
            url: ROUTES.MONOLITHIC_CONCRETE_STRUCTURES,
            mobileImg: '/monolithicConcreteStructuresMobile.png',
            desc: t("servicesPage.monolithicConcreteStructures.desc"),
            desktopImg: '/monolithicConcreteStructuresBig.jpg',
            name: t("servicesPage.monolithicConcreteStructures.name"),
            smallDesc: t("servicesPage.monolithicConcreteStructures.smallDesc"),
            additionTitle: t("servicesPage.monolithicConcreteStructures.additionTitle"),
            additionTitleList: [
                {
                    id: 1,
                    title: t("servicesPage.monolithicConcreteStructures.title_1"),
                    text: t("servicesPage.monolithicConcreteStructures.addition_1"),
                },
                {
                    id: 2,
                    title: t("servicesPage.monolithicConcreteStructures.title_2"),
                    text: t("servicesPage.monolithicConcreteStructures.addition_2"),
                },
                {
                    id: 3,
                    title: t("servicesPage.monolithicConcreteStructures.title_3"),
                    text: t("servicesPage.monolithicConcreteStructures.addition_3"),
                },
                {
                    id: 4,
                    title: t("servicesPage.monolithicConcreteStructures.title_4"),
                    text: t("servicesPage.monolithicConcreteStructures.addition_4"),
                },
                {
                    id: 5,
                    title: t("servicesPage.monolithicConcreteStructures.title_5"),
                    text: t("servicesPage.monolithicConcreteStructures.addition_5"),
                },
            ],
            additionImg: '/monolithicConcreteStructuresOne.png',
            supportStructuresTitle: t("servicesPage.monolithicConcreteStructures.supportStructuresTitle"),
            supportStructures_1: t("servicesPage.monolithicConcreteStructures.supportStructures_1"),
            supportStructures_2: t("servicesPage.monolithicConcreteStructures.supportStructures_2"),
        },
        {
            id: 12,
            url: ROUTES.STEEL_STRUCTURE_INSTALLATION,
            mobileImg: '/steelStructureInstallationMobile.jpg',
            desc: t("servicesPage.steelStructureInstallation.desc"),
            desktopImg: '/steelStructureInstallationBig.jpg',
            name: t("servicesPage.steelStructureInstallation.name"),
            smallDesc: t("servicesPage.steelStructureInstallation.smallDesc"),
            additionTitle: t("servicesPage.steelStructureInstallation.additionTitle"),
            additionTitleList: [
                {
                    id: 1,
                    title: t("servicesPage.steelStructureInstallation.title_1"),
                    text: t("servicesPage.steelStructureInstallation.addition_1"),
                },
                {
                    id: 2,
                    title: t("servicesPage.steelStructureInstallation.title_2"),
                    text: t("servicesPage.steelStructureInstallation.addition_2"),
                },
                {
                    id: 3,
                    title: t("servicesPage.steelStructureInstallation.title_3"),
                    text: t("servicesPage.steelStructureInstallation.addition_3"),
                },
                {
                    id: 4,
                    title: t("servicesPage.steelStructureInstallation.title_4"),
                    text: t("servicesPage.steelStructureInstallation.addition_4"),
                },
                {
                    id: 5,
                    title: t("servicesPage.steelStructureInstallation.title_5"),
                    text: t("servicesPage.steelStructureInstallation.addition_5"),
                },
                {
                    id: 6,
                    title: t("servicesPage.steelStructureInstallation.title_6"),
                    text: t("servicesPage.steelStructureInstallation.addition_6"),
                },
                {
                    id: 7,
                    title: t("servicesPage.steelStructureInstallation.title_7"),
                    text: t("servicesPage.steelStructureInstallation.addition_7"),
                },
                {
                    id: 8,
                    title: t("servicesPage.steelStructureInstallation.title_8"),
                    text: t("servicesPage.steelStructureInstallation.addition_8"),
                },
                {
                    id: 9,
                    title: t("servicesPage.steelStructureInstallation.title_9"),
                    text: t("servicesPage.steelStructureInstallation.addition_9"),
                },
                {
                    id: 10,
                    title: t("servicesPage.steelStructureInstallation.title_10"),
                    text: t("servicesPage.steelStructureInstallation.addition_10"),
                },
                {
                    id: 11,
                    title: t("servicesPage.steelStructureInstallation.title_11"),
                    text: t("servicesPage.steelStructureInstallation.addition_11"),
                },
                {
                    id: 12,
                    title: t("servicesPage.steelStructureInstallation.title_12"),
                    text: t("servicesPage.steelStructureInstallation.addition_12"),
                },
            ],
            additionImg: '/steelStructureInstallationOne.jpg',
            supportStructuresTitle: t("servicesPage.steelStructureInstallation.supportStructuresTitle"),
            supportStructures_1: t("servicesPage.steelStructureInstallation.supportStructures_1"),
            supportStructures_2: t("servicesPage.steelStructureInstallation.supportStructures_2"),
        },
        {
            id: 13,
            url: ROUTES.LIGHT_ENCLOSING_STRUCTURES_INSTALLATION,
            mobileImg: '/lightEnclosingStructuresInstallationMobile.png',
            desc: t("servicesPage.lightEnclosingStructuresInstallation.desc"),
            desktopImg: '/lightEnclosingStructuresInstallationBig.jpg',
            name: t("servicesPage.lightEnclosingStructuresInstallation.name"),
            smallDesc: t("servicesPage.lightEnclosingStructuresInstallation.smallDesc"),
            additionTitle: t("servicesPage.lightEnclosingStructuresInstallation.additionTitle"),
            additionTitleList: [
                {
                    id: 1,
                    title: t("servicesPage.lightEnclosingStructuresInstallation.title_1"),
                    text: t("servicesPage.lightEnclosingStructuresInstallation.addition_1"),
                },
                {
                    id: 2,
                    title: t("servicesPage.lightEnclosingStructuresInstallation.title_2"),
                    text: t("servicesPage.lightEnclosingStructuresInstallation.addition_2"),
                },
                {
                    id: 3,
                    title: t("servicesPage.lightEnclosingStructuresInstallation.title_3"),
                    text: t("servicesPage.lightEnclosingStructuresInstallation.addition_3"),
                },
                {
                    id: 4,
                    title: t("servicesPage.lightEnclosingStructuresInstallation.title_4"),
                    text: t("servicesPage.lightEnclosingStructuresInstallation.addition_4"),
                },
                {
                    id: 5,
                    title: t("servicesPage.lightEnclosingStructuresInstallation.title_5"),
                    text: t("servicesPage.lightEnclosingStructuresInstallation.addition_5"),
                },
                {
                    id: 6,
                    title: t("servicesPage.lightEnclosingStructuresInstallation.title_6"),
                    text: t("servicesPage.lightEnclosingStructuresInstallation.addition_6"),
                },
            ],
            additionImg: '/lightEnclosingStructuresInstallationOne.jpg',
            supportStructuresTitle: t("servicesPage.lightEnclosingStructuresInstallation.supportStructuresTitle"),
            supportStructures_1: t("servicesPage.lightEnclosingStructuresInstallation.supportStructures_1"),
            supportStructures_2: t("servicesPage.lightEnclosingStructuresInstallation.supportStructures_2"),
        },
        {
            id: 14,
            url: ROUTES.ROOFING_INSTALLATION,
            mobileImg: '/roofingInstallationMobile.jpg',
            desc: t("servicesPage.roofingInstallation.desc"),
            desktopImg: '/roofingInstallationBig.jpg',
            name: t("servicesPage.roofingInstallation.name"),
            smallDesc: t("servicesPage.roofingInstallation.smallDesc"),
            additionTitle: t("servicesPage.roofingInstallation.additionTitle"),
            additionTitleList: [
                {
                    id: 1,
                    title: t("servicesPage.roofingInstallation.title_1"),
                    text: t("servicesPage.roofingInstallation.addition_1"),
                },
                {
                    id: 2,
                    title: t("servicesPage.roofingInstallation.title_2"),
                    text: t("servicesPage.roofingInstallation.addition_2"),
                },
                {
                    id: 3,
                    title: t("servicesPage.roofingInstallation.title_3"),
                    text: t("servicesPage.roofingInstallation.addition_3"),
                },
                {
                    id: 4,
                    title: t("servicesPage.roofingInstallation.title_4"),
                    text: t("servicesPage.roofingInstallation.addition_4"),
                },
                {
                    id: 5,
                    title: t("servicesPage.roofingInstallation.title_5"),
                    text: t("servicesPage.roofingInstallation.addition_5"),
                },
                {
                    id: 6,
                    title: t("servicesPage.roofingInstallation.title_6"),
                    text: t("servicesPage.roofingInstallation.addition_6"),
                },
            ],
            additionImg: '/roofingInstallationOne.jpg',
            supportStructuresTitle: t("servicesPage.roofingInstallation.supportStructuresTitle"),
            supportStructures_1: t("servicesPage.roofingInstallation.supportStructures_1"),
            supportStructures_2: t("servicesPage.roofingInstallation.supportStructures_2"),
        },
        {
            id: 15,
            url: ROUTES.THERMAL_INSULATION,
            mobileImg: '/thermalInsulationMobile.png',
            desc: t("servicesPage.thermalInsulation.desc"),
            desktopImg: '/thermalInsulationBig.jpg',
            name: t("servicesPage.thermalInsulation.name"),
            smallDesc: t("servicesPage.thermalInsulation.smallDesc"),
            additionTitle: t("servicesPage.thermalInsulation.additionTitle"),
            additionTitleList: [
                {
                    id: 1,
                    title: t("servicesPage.thermalInsulation.title_1"),
                    text: t("servicesPage.thermalInsulation.addition_1"),
                },
                {
                    id: 2,
                    title: t("servicesPage.thermalInsulation.title_2"),
                    text: t("servicesPage.thermalInsulation.addition_2"),
                },
                {
                    id: 3,
                    title: t("servicesPage.thermalInsulation.title_3"),
                    text: t("servicesPage.thermalInsulation.addition_3"),
                },
                {
                    id: 4,
                    title: t("servicesPage.thermalInsulation.title_4"),
                    text: t("servicesPage.thermalInsulation.addition_4"),
                },
                {
                    id: 5,
                    title: t("servicesPage.thermalInsulation.title_5"),
                    text: t("servicesPage.thermalInsulation.addition_5"),
                },
                {
                    id: 6,
                    title: t("servicesPage.thermalInsulation.title_6"),
                    text: t("servicesPage.thermalInsulation.addition_6"),
                },
            ],
            additionImg: '/thermalInsulationOne.jpg',
            supportStructuresTitle: t("servicesPage.thermalInsulation.supportStructuresTitle"),
            supportStructures_1: t("servicesPage.thermalInsulation.supportStructures_1"),
            supportStructures_2: t("servicesPage.thermalInsulation.supportStructures_2"),
        },
        {
            id: 16,
            url: ROUTES.THERMAL_INSULATION_EQUIPMENT,
            mobileImg: '/thermalInsulationEquipmentMobile.png',
            desc: t("servicesPage.thermalInsulationEquipment.desc"),
            desktopImg: '/thermalInsulationEquipmentBig.jpg',
            name: t("servicesPage.thermalInsulationEquipment.name"),
            smallDesc: t("servicesPage.thermalInsulationEquipment.smallDesc"),
            additionTitle: t("servicesPage.thermalInsulationEquipment.additionTitle"),
            additionTitleList: [
                {
                    id: 1,
                    title: t("servicesPage.thermalInsulationEquipment.title_1"),
                    text: t("servicesPage.thermalInsulationEquipment.addition_1"),
                },
                {
                    id: 2,
                    title: t("servicesPage.thermalInsulationEquipment.title_2"),
                    text: t("servicesPage.thermalInsulationEquipment.addition_2"),
                },
                {
                    id: 3,
                    title: t("servicesPage.thermalInsulationEquipment.title_3"),
                    text: t("servicesPage.thermalInsulationEquipment.addition_3"),
                },
                {
                    id: 4,
                    title: t("servicesPage.thermalInsulationEquipment.title_4"),
                    text: t("servicesPage.thermalInsulationEquipment.addition_4"),
                },
                {
                    id: 5,
                    title: t("servicesPage.thermalInsulationEquipment.title_5"),
                    text: t("servicesPage.thermalInsulationEquipment.addition_5"),
                },
            ],
            additionImg: '/thermalInsulationEquipmentOne.png',
            supportStructuresTitle: t("servicesPage.thermalInsulationEquipment.supportStructuresTitle"),
            supportStructures_1: t("servicesPage.thermalInsulationEquipment.supportStructures_1"),
            supportStructures_2: t("servicesPage.thermalInsulationEquipment.supportStructures_2"),
        },
        {
            id: 17,
            url: ROUTES.FINISHING_WORKS,
            mobileImg: '/finishingWorksMobile.jpg',
            desc: t("servicesPage.finishingWorks.desc"),
            desktopImg: '/finishingWorksBig.jpg',
            name: t("servicesPage.finishingWorks.name"),
            smallDesc: t("servicesPage.finishingWorks.smallDesc"),
            additionTitle: t("servicesPage.finishingWorks.additionTitle"),
            additionTitleList: [
                {
                    id: 1,
                    title: t("servicesPage.finishingWorks.title_1"),
                    text: t("servicesPage.finishingWorks.addition_1"),
                },
                {
                    id: 2,
                    title: t("servicesPage.finishingWorks.title_2"),
                    text: t("servicesPage.finishingWorks.addition_2"),
                },
                {
                    id: 3,
                    title: t("servicesPage.finishingWorks.title_3"),
                    text: t("servicesPage.finishingWorks.addition_3"),
                },
                {
                    id: 4,
                    title: t("servicesPage.finishingWorks.title_4"),
                    text: t("servicesPage.finishingWorks.addition_4"),
                },
                {
                    id: 5,
                    title: t("servicesPage.finishingWorks.title_5"),
                    text: t("servicesPage.finishingWorks.addition_5"),
                },
            ],
            additionImg: '/finishingWorksOne.jpg',
            supportStructuresTitle: t("servicesPage.finishingWorks.supportStructuresTitle"),
            supportStructures_1: t("servicesPage.finishingWorks.supportStructures_1"),
            supportStructures_2: t("servicesPage.finishingWorks.supportStructures_2"),
        },
        {
            id: 18,
            url: ROUTES.WINDOW_AND_DOOR_FRAMES_FILLING,
            mobileImg: '/windowAndDoorFramesFillingMobile.png',
            desc: t("servicesPage.windowAndDoorFramesFilling.desc"),
            desktopImg: '/windowAndDoorFramesFillingBig.jpg',
            name: t("servicesPage.windowAndDoorFramesFilling.name"),
            smallDesc: t("servicesPage.windowAndDoorFramesFilling.smallDesc"),
            additionTitle: t("servicesPage.windowAndDoorFramesFilling.additionTitle"),
            additionTitleList: [
                {
                    id: 1,
                    title: t("servicesPage.windowAndDoorFramesFilling.title_1"),
                    text: t("servicesPage.windowAndDoorFramesFilling.addition_1"),
                },
                {
                    id: 2,
                    title: t("servicesPage.windowAndDoorFramesFilling.title_2"),
                    text: t("servicesPage.windowAndDoorFramesFilling.addition_2"),
                },
                {
                    id: 3,
                    title: t("servicesPage.windowAndDoorFramesFilling.title_3"),
                    text: t("servicesPage.windowAndDoorFramesFilling.addition_3"),
                },
            ],
            additionImg: '/windowAndDoorFramesFillingOne.jpg',
            supportStructuresTitle: t("servicesPage.windowAndDoorFramesFilling.supportStructuresTitle"),
            supportStructures_1: t("servicesPage.windowAndDoorFramesFilling.supportStructures_1"),
            supportStructures_2: t("servicesPage.windowAndDoorFramesFilling.supportStructures_2"),
        },
        {
            id: 19,
            url: ROUTES.FLOOR_INSTALLATION,
            mobileImg: '/floorInstallationMobile.jpg',
            desc: t("servicesPage.floorInstallation.desc"),
            desktopImg: '/floorInstallationBig.jpg',
            name: t("servicesPage.floorInstallation.name"),
            smallDesc: t("servicesPage.floorInstallation.smallDesc"),
            additionTitle: t("servicesPage.floorInstallation.additionTitle"),
            additionTitleList: [
                {
                    id: 1,
                    title: t("servicesPage.floorInstallation.title_1"),
                    text: t("servicesPage.floorInstallation.addition_1"),
                },
                {
                    id: 2,
                    title: t("servicesPage.floorInstallation.title_2"),
                    text: t("servicesPage.floorInstallation.addition_2"),
                },
                {
                    id: 3,
                    title: t("servicesPage.floorInstallation.title_3"),
                    text: t("servicesPage.floorInstallation.addition_3"),
                },
                {
                    id: 4,
                    title: t("servicesPage.floorInstallation.title_4"),
                    text: t("servicesPage.floorInstallation.addition_4"),
                },
                {
                    id: 5,
                    title: t("servicesPage.floorInstallation.title_5"),
                    text: t("servicesPage.floorInstallation.addition_5"),
                },
                {
                    id: 6,
                    title: t("servicesPage.floorInstallation.title_6"),
                    text: t("servicesPage.floorInstallation.addition_6"),
                },
                {
                    id: 7,
                    title: t("servicesPage.floorInstallation.title_7"),
                    text: t("servicesPage.floorInstallation.addition_7"),
                },
                {
                    id: 8,
                    title: t("servicesPage.floorInstallation.title_8"),
                    text: t("servicesPage.floorInstallation.addition_8"),
                },
                {
                    id: 9,
                    title: t("servicesPage.floorInstallation.title_9"),
                    text: t("servicesPage.floorInstallation.addition_9"),
                },
                {
                    id: 10,
                    title: t("servicesPage.floorInstallation.title_10"),
                    text: t("servicesPage.floorInstallation.addition_10"),
                },
                {
                    id: 11,
                    title: t("servicesPage.floorInstallation.title_11"),
                    text: t("servicesPage.floorInstallation.addition_11"),
                },
                {
                    id: 12,
                    title: t("servicesPage.floorInstallation.title_12"),
                    text: t("servicesPage.floorInstallation.addition_12"),
                },
            ],
            additionImg: '/floorInstallationOne.jpg',
            supportStructuresTitle: t("servicesPage.floorInstallation.supportStructuresTitle"),
            supportStructures_1: t("servicesPage.floorInstallation.supportStructures_1"),
            supportStructures_2: t("servicesPage.floorInstallation.supportStructures_2"),
        },
        {
            id: 20,
            url: ROUTES.EQUIPMENT_INSTALLATION,
            mobileImg: '/equipmentInstallationMobile.jpg',
            desc: t("servicesPage.equipmentInstallation.desc"),
            desktopImg: '/equipmentInstallationBig.jpg',
            name: t("servicesPage.equipmentInstallation.name"),
            smallDesc: t("servicesPage.equipmentInstallation.smallDesc"),
            additionTitle: t("servicesPage.equipmentInstallation.additionTitle"),
            additionTitleList: [
                {
                    id: 1,
                    title: t("servicesPage.equipmentInstallation.title_1"),
                    text: t("servicesPage.equipmentInstallation.addition_1"),
                },
                {
                    id: 2,
                    title: t("servicesPage.equipmentInstallation.title_2"),
                    text: t("servicesPage.equipmentInstallation.addition_2"),
                },
                {
                    id: 3,
                    title: t("servicesPage.equipmentInstallation.title_3"),
                    text: t("servicesPage.equipmentInstallation.addition_3"),
                },
                {
                    id: 4,
                    title: t("servicesPage.equipmentInstallation.title_4"),
                    text: t("servicesPage.equipmentInstallation.addition_4"),
                },
                {
                    id: 5,
                    title: t("servicesPage.equipmentInstallation.title_5"),
                    text: t("servicesPage.equipmentInstallation.addition_5"),
                },
                {
                    id: 6,
                    title: t("servicesPage.equipmentInstallation.title_6"),
                    text: t("servicesPage.equipmentInstallation.addition_6"),
                },
                {
                    id: 7,
                    title: t("servicesPage.equipmentInstallation.title_7"),
                    text: t("servicesPage.equipmentInstallation.addition_7"),
                },
                {
                    id: 8,
                    title: t("servicesPage.equipmentInstallation.title_8"),
                    text: t("servicesPage.equipmentInstallation.addition_8"),
                },
                {
                    id: 9,
                    title: t("servicesPage.equipmentInstallation.title_9"),
                    text: t("servicesPage.equipmentInstallation.addition_9"),
                },
                {
                    id: 10,
                    title: t("servicesPage.equipmentInstallation.title_10"),
                    text: t("servicesPage.equipmentInstallation.addition_10"),
                },
            ],
            additionImg: '/equipmentInstallationOne.jpg',
            supportStructuresTitle: t("servicesPage.equipmentInstallation.supportStructuresTitle"),
            supportStructures_1: t("servicesPage.equipmentInstallation.supportStructures_1"),
            supportStructures_2: t("servicesPage.equipmentInstallation.supportStructures_2"),
        },
        {
            id: 21,
            url: ROUTES.PIPELINE_INSTALLATION,
            mobileImg: '/pipelineInstallationMobile.jpg',
            desc: t("servicesPage.pipelineInstallation.desc"),
            desktopImg: '/pipelineInstallationBig.jpg',
            name: t("servicesPage.pipelineInstallation.name"),
            smallDesc: t("servicesPage.pipelineInstallation.smallDesc"),
            additionTitle: t("servicesPage.pipelineInstallation.additionTitle"),
            additionTitleList: [
                {
                    id: 1,
                    title: t("servicesPage.pipelineInstallation.title_1"),
                    text: t("servicesPage.pipelineInstallation.addition_1"),
                },
                {
                    id: 2,
                    title: t("servicesPage.pipelineInstallation.title_2"),
                    text: t("servicesPage.pipelineInstallation.addition_2"),
                },
                {
                    id: 3,
                    title: t("servicesPage.pipelineInstallation.title_3"),
                    text: t("servicesPage.pipelineInstallation.addition_3"),
                },
            ],
            additionImg: '/pipelineInstallationOne.png',
            supportStructuresTitle: t("servicesPage.pipelineInstallation.supportStructuresTitle"),
            supportStructures_1: t("servicesPage.pipelineInstallation.supportStructures_1"),
            supportStructures_2: t("servicesPage.pipelineInstallation.supportStructures_2"),
        },
        {
            id: 22,
            url: ROUTES.INTERNAL_SYSTEMS_INSTALLATION,
            mobileImg: '/internalSystemsInstallationMobile.jpg',
            desc: t("servicesPage.internalSystemsInstallation.desc"),
            desktopImg: '/internalSystemsInstallationBig.jpg',
            name: t("servicesPage.internalSystemsInstallation.name"),
            smallDesc: t("servicesPage.internalSystemsInstallation.smallDesc"),
            additionTitle: t("servicesPage.internalSystemsInstallation.additionTitle"),
            additionTitleList: [
                {
                    id: 1,
                    text: t("servicesPage.internalSystemsInstallation.addition_1"),
                },
                {
                    id: 2,
                    text: t("servicesPage.internalSystemsInstallation.addition_2"),
                },
                {
                    id: 3,
                    text: t("servicesPage.internalSystemsInstallation.addition_3"),
                },
                {
                    id: 4,
                    text: t("servicesPage.internalSystemsInstallation.addition_4"),
                },
                {
                    id: 5,
                    text: t("servicesPage.internalSystemsInstallation.addition_5"),
                },
                {
                    id: 6,
                    text: t("servicesPage.internalSystemsInstallation.addition_6"),
                },
                {
                    id: 7,
                    text: t("servicesPage.internalSystemsInstallation.addition_7"),
                },
            ],
            additionImg: '/internalSystemsInstallationOne.jpg',
            supportStructuresTitle: t("servicesPage.internalSystemsInstallation.supportStructuresTitle"),
            supportStructures_1: t("servicesPage.internalSystemsInstallation.supportStructures_1"),
            supportStructures_2: t("servicesPage.internalSystemsInstallation.supportStructures_2"),
        },
        {
            id: 23,
            url: ROUTES.EXTERNAL_NETWORKS_INSTALLATION,
            mobileImg: '/externalNetworksInstallationMobile.jpg',
            desc: t("servicesPage.externalNetworksInstallation.desc"),
            desktopImg: '/externalNetworksInstallationBig.jpg',
            name: t("servicesPage.externalNetworksInstallation.name"),
            smallDesc: t("servicesPage.externalNetworksInstallation.smallDesc"),
            additionTitle: t("servicesPage.externalNetworksInstallation.additionTitle"),
            additionTitleList: [
                {
                    id: 1,
                    title: t("servicesPage.externalNetworksInstallation.title_1"),
                    text: t("servicesPage.externalNetworksInstallation.addition_1"),
                },
                {
                    id: 2,
                    title: t("servicesPage.externalNetworksInstallation.title_2"),
                    text: t("servicesPage.externalNetworksInstallation.addition_2"),
                },
                {
                    id: 3,
                    title: t("servicesPage.externalNetworksInstallation.title_3"),
                    text: t("servicesPage.externalNetworksInstallation.addition_3"),
                },
                {
                    id: 4,
                    title: t("servicesPage.externalNetworksInstallation.title_4"),
                    text: t("servicesPage.externalNetworksInstallation.addition_4"),
                },
                {
                    id: 5,
                    title: t("servicesPage.externalNetworksInstallation.title_5"),
                    text: t("servicesPage.externalNetworksInstallation.addition_5"),
                },
            ],
            additionImg: '/externalNetworksInstallationOne.png',
            supportStructuresTitle: t("servicesPage.externalNetworksInstallation.supportStructuresTitle"),
            supportStructures_1: t("servicesPage.externalNetworksInstallation.supportStructures_1"),
            supportStructures_2: t("servicesPage.externalNetworksInstallation.supportStructures_2"),
        },
        {
            id: 24,
            url: ROUTES.HEAT_METER_INSTALLATION,
            mobileImg: '/heatMeterInstallationMobile.jpg',
            desc: t("servicesPage.heatMeterInstallation.desc"),
            desktopImg: '/heatMeterInstallationBig.jpg',
            name: t("servicesPage.heatMeterInstallation.name"),
            smallDesc: t("servicesPage.heatMeterInstallation.smallDesc"),
            additionTitle: t("servicesPage.heatMeterInstallation.additionTitle"),
            additionTitleList: [
                {
                    id: 1,
                    title: t("servicesPage.heatMeterInstallation.title_1"),
                    text: t("servicesPage.heatMeterInstallation.addition_1"),
                },
                {
                    id: 2,
                    title: t("servicesPage.heatMeterInstallation.title_2"),
                    text: t("servicesPage.heatMeterInstallation.addition_2"),
                },
                {
                    id: 3,
                    title: t("servicesPage.heatMeterInstallation.title_3"),
                    text: t("servicesPage.heatMeterInstallation.addition_3"),
                },
                {
                    id: 4,
                    title: t("servicesPage.heatMeterInstallation.title_4"),
                    text: t("servicesPage.heatMeterInstallation.addition_4"),
                },
            ],
            additionImg: '/heatMeterInstallationOne.png',
            supportStructuresTitle: t("servicesPage.heatMeterInstallation.supportStructuresTitle"),
            supportStructures_1: t("servicesPage.heatMeterInstallation.supportStructures_1"),
            supportStructures_2: t("servicesPage.heatMeterInstallation.supportStructures_2"),
        },
        {
            id: 25,
            url: ROUTES.ELECTRICAL_INSTALLATION,
            mobileImg: '/electricalInstallationMobile.jpg',
            desc: t("servicesPage.electricalInstallation.desc"),
            desktopImg: '/electricalInstallationBig.jpg',
            name: t("servicesPage.electricalInstallation.name"),
            smallDesc: t("servicesPage.electricalInstallation.smallDesc"),
            additionTitle: t("servicesPage.electricalInstallation.additionTitle"),
            additionTitleList: [
                {
                    id: 1,
                    title: t("servicesPage.electricalInstallation.title_1"),
                    text: t("servicesPage.electricalInstallation.addition_1"),
                },
                {
                    id: 2,
                    title: t("servicesPage.electricalInstallation.title_2"),
                    text: t("servicesPage.electricalInstallation.addition_2"),
                },
                {
                    id: 3,
                    title: t("servicesPage.electricalInstallation.title_3"),
                    text: t("servicesPage.electricalInstallation.addition_3"),
                },
                {
                    id: 4,
                    title: t("servicesPage.electricalInstallation.title_4"),
                    text: t("servicesPage.electricalInstallation.addition_4"),
                },
                {
                    id: 5,
                    title: t("servicesPage.electricalInstallation.title_5"),
                    text: t("servicesPage.electricalInstallation.addition_5"),
                },
            ],
            additionImg: '/electricalInstallationOne.jpg',
            supportStructuresTitle: t("servicesPage.electricalInstallation.supportStructuresTitle"),
            supportStructures_1: t("servicesPage.electricalInstallation.supportStructures_1"),
            supportStructures_2: t("servicesPage.electricalInstallation.supportStructures_2"),
        },
        {
            id: 26,
            url: ROUTES.AUTOMATION_SYSTEMS_INSTALLATION,
            mobileImg: '/automationSystemsInstallationMobile.jpg',
            desc: t("servicesPage.automationSystemsInstallation.desc"),
            desktopImg: '/automationSystemsInstallationBig.jpg',
            name: t("servicesPage.automationSystemsInstallation.name"),
            smallDesc: t("servicesPage.automationSystemsInstallation.smallDesc"),
            additionTitle: t("servicesPage.automationSystemsInstallation.additionTitle"),
            additionTitleList: [
                {
                    id: 1,
                    title: t("servicesPage.automationSystemsInstallation.title_1"),
                    text: t("servicesPage.automationSystemsInstallation.addition_1"),
                },
                {
                    id: 2,
                    title: t("servicesPage.automationSystemsInstallation.title_2"),
                    text: t("servicesPage.automationSystemsInstallation.addition_2"),
                },
                {
                    id: 3,
                    title: t("servicesPage.automationSystemsInstallation.title_3"),
                    text: t("servicesPage.automationSystemsInstallation.addition_3"),
                },
                {
                    id: 4,
                    title: t("servicesPage.automationSystemsInstallation.title_4"),
                    text: t("servicesPage.automationSystemsInstallation.addition_4"),
                },
                {
                    id: 5,
                    title: t("servicesPage.automationSystemsInstallation.title_5"),
                    text: t("servicesPage.automationSystemsInstallation.addition_5"),
                },
                {
                    id: 6,
                    title: t("servicesPage.automationSystemsInstallation.title_6"),
                    text: t("servicesPage.automationSystemsInstallation.addition_6"),
                },
            ],
            additionImg: '/automationSystemsInstallationOne.jpg',
            supportStructuresTitle: t("servicesPage.automationSystemsInstallation.supportStructuresTitle"),
            supportStructures_1: t("servicesPage.automationSystemsInstallation.supportStructures_1"),
            supportStructures_2: t("servicesPage.automationSystemsInstallation.supportStructures_2"),
        },
    ]
})