export const ROUTES = {
    HOME: "/",
    NOT_FOUND: "/notfound",
    ABOUT_US: "/about-us",
    CONTACTS: "/contacts",
    FAQ: "/faq",
    PORTFOLIO: "/portfolio",
    PRIVACY_POLICY: "/privacy-policy",

    SERVICE: "/service/:id",
    SERVICES: "/services",
    BUSINESS_CARD_WEBSITE: "business-card-website",
    ADJUSTMENT_OF_GAS_DISTRIBUTION_SYSTEM: "adjustmentOfGasDistributionSystem",
    ADJUSTMENT_OF_EQUIPMENT_UNDER_EXCESS_PRESSURE: "adjustmentOfEquipmentUnderExcessPressure",
    ADJUSTMENT_OF_TECHNICAL_DEVICES: "adjustmentOfTechnicalDevices",
    MAINTENANCE_OF_GAS_DISTRIBUTION_SYSTEM: "maintenanceOfGasDistributionSystem",
    SERVICING_EQUIPMENT_UNDER_EXCESS_PRESSURE: "servicingEquipmentUnderExcessPressure",
    MAINTENANCE_OF_TECHNICAL_DEVICES: "maintenanceOfTechnicalDevices",
    INSTALLATION_OF_EQUIPMENT_UNDER_EXCESS_PRESSURE: "installationOfEquipmentUnderExcessPressure",
    INSTALLATION_OF_TECHNICAL_DEVICES: "installationOfTechnicalDevices",
    INSTALLATION_OF_GAS_DISTRIBUTION_SYSTEM_FACILITIES: "installationOfGasDistributionSystemFacilities",
    FOUNDATION_CONSTRUCTION: "foundationConstruction",
    MONOLITHIC_CONCRETE_STRUCTURES: "monolithicConcreteStructures",
    STEEL_STRUCTURE_INSTALLATION: "steelStructureInstallation",
    LIGHT_ENCLOSING_STRUCTURES_INSTALLATION: "lightEnclosingStructuresInstallation",
    ROOFING_INSTALLATION: "roofingInstallation",
    THERMAL_INSULATION: "thermalInsulation",
    THERMAL_INSULATION_EQUIPMENT: "thermalInsulationEquipment",
    FINISHING_WORKS: "finishingWorks",
    WINDOW_AND_DOOR_FRAMES_FILLING: "windowAndDoorFramesFilling",
    FLOOR_INSTALLATION: "floorInstallation",
    EQUIPMENT_INSTALLATION: "equipmentInstallation",
    PIPELINE_INSTALLATION: "pipelineInstallation",
    INTERNAL_SYSTEMS_INSTALLATION: "internalSystemsInstallation",
    EXTERNAL_NETWORKS_INSTALLATION: "externalNetworksInstallation",
    HEAT_METER_INSTALLATION: "heatMeterInstallation",
    ELECTRICAL_INSTALLATION: "electricalInstallation",
    AUTOMATION_SYSTEMS_INSTALLATION: "automationSystemsInstallation",


}